/*
 * newtrain.java
 *
 * Created on __DATE__, __TIME__
 */

package admin;

import server.Client;

import javax.swing.*;
import java.io.IOException;

/**
 *
 * @author  __USER__
 */
public class newtrain extends javax.swing.JFrame {

    /** Creates new form newtrain */
    public newtrain() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    //GEN-BEGIN:initComponents
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        train_number = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        startlocat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        startlocat1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        starttime = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        endtime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        business = new javax.swing.JTextField();
        kkk = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        oneset = new javax.swing.JTextField();
        twoset = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        oneset1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        businessprice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        one_price = new javax.swing.JTextField();
        twoprice = new javax.swing.JTextField();
        standprice = new javax.swing.JTextField();
        this.setTitle("添加列车信息");
        jPanel1.setBackground(new java.awt.Color(255, 179, 179));

        jLabel1.setIcon(new ImageIcon(
                "src/icon/icons8-calendar-28-16.png")); // NOI18N
        jLabel1.setText("\u51fa\u53d1\u65e5\u671f");

        jLabel2.setIcon(new ImageIcon(
                "src/icon/icons8-calendar-28-16.png")); // NOI18N
        jLabel2.setText("\u5230\u8fbe\u65e5\u671f");

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 18));
        jLabel3.setIcon(new ImageIcon(
                "src/icon/icons8-train-50.png")); // NOI18N
        jLabel3.setText("\u6dfb\u52a0\u5217\u8f66\u4fe1\u606f");

        jLabel4.setIcon(new ImageIcon(
                "src/icon/icons8-subway-16.png")); // NOI18N
        jLabel4.setText("\u8f66\u6b21");

        jLabel5.setIcon(new ImageIcon(
                "src/icon/icons8-location-16.png")); // NOI18N
        jLabel5.setText("\u51fa\u53d1\u5730");

        jLabel6.setIcon(new ImageIcon(
                "src/icon/icons8-location-16.png")); // NOI18N
        jLabel6.setText("\u76ee\u7684\u5730");

        jLabel7.setIcon(new ImageIcon(
                "src/icon/icons8-time-machine-16.png")); // NOI18N
        jLabel7.setText("\u51fa\u53d1\u65f6\u95f4");

        jLabel8.setIcon(new ImageIcon(
                "src/icon/icons8-time-machine-16.png")); // NOI18N
        jLabel8.setText("\u5230\u8fbe\u65f6\u95f4");

        jLabel9.setIcon(new ImageIcon(
                "src/icon/icons8-theatre-seat-16.png")); // NOI18N
        jLabel9.setText("\u5546\u52a1\u5ea7");

        kkk.setIcon(new ImageIcon(
                "src/icon/icons8-theatre-seat-16.png")); // NOI18N
        kkk.setText("\u4e00\u7b49\u5ea7");

        jLabel11.setIcon(new ImageIcon(
                "src/icon/icons8-theatre-seat-16.png")); // NOI18N
        jLabel11.setText("\u4e8c\u7b49\u5ea7");

        jLabel12.setIcon(new ImageIcon(
                "src/icon/icons8-theatre-seat-16.png")); // NOI18N
        jLabel12.setText("\u65e0\u5ea7");

        jButton1.setBackground(new java.awt.Color(252, 197, 197));
        jButton1.setIcon(new ImageIcon(
                "src/icon/icons8-kicking-16.png")); // NOI18N
        jButton1.setText("\u589e\u52a0\u5217\u8f66");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButton1ActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });

        jLabel10.setIcon(new ImageIcon(
                "src/icon/icons8-token-card-code-16.png")); // NOI18N
        jLabel10.setText("\u5546\u52a1\u5ea7\u4ef7\u683c");

        jLabel13.setIcon(new ImageIcon(
                "src/icon/icons8-token-card-code-16.png")); // NOI18N
        jLabel13.setText("\u4e00\u7b49\u5ea7\u4ef7\u683c");

        jLabel14.setIcon(new ImageIcon(
                "src/icon/icons8-token-card-code-16.png")); // NOI18N
        jLabel14.setText("\u4e8c\u7b49\u5ea7\u4ef7\u683c");

        jLabel15.setIcon(new ImageIcon(
                "src/icon/icons8-token-card-code-16.png")); // NOI18N
        jLabel15.setText("\u65e0\u5ea7\u4ef7\u683c");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
                jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout
                .setHorizontalGroup(jPanel1Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel1Layout.createSequentialGroup().addGap(
                                        195, 195, 195).addComponent(jButton1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        115,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(171, Short.MAX_VALUE))
                        .addGroup(
                                jPanel1Layout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(
                                                jLabel3,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                176,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(293, Short.MAX_VALUE))
                        .addGroup(
                                jPanel1Layout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(
                                                standprice,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                132, Short.MAX_VALUE).addGap(
                                        251, 251, 251))
                        .addGroup(
                                jPanel1Layout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(
                                                                jPanel1Layout
                                                                        .createSequentialGroup()
                                                                        .addGroup(
                                                                                jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(
                                                                                                jLabel1)
                                                                                        .addComponent(
                                                                                                jLabel4)
                                                                                        .addComponent(
                                                                                                jLabel6))
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addGroup(
                                                                                jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(
                                                                                                train_number,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                144,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(
                                                                                                date,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                144,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(
                                                                                                startlocat,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                144,
                                                                                                Short.MAX_VALUE)))
                                                        .addGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                jPanel1Layout
                                                                        .createSequentialGroup()
                                                                        .addGroup(
                                                                                jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(
                                                                                                jLabel12)
                                                                                        .addComponent(
                                                                                                kkk)
                                                                                        .addComponent(
                                                                                                jLabel8))
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addGroup(
                                                                                jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(
                                                                                                oneset1,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                144,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(
                                                                                                endtime,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                144,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(
                                                                                                oneset,
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                144,
                                                                                                Short.MAX_VALUE)))
                                                        .addGroup(
                                                                jPanel1Layout
                                                                        .createSequentialGroup()
                                                                        .addComponent(
                                                                                jLabel13)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(
                                                                                one_price,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                132,
                                                                                Short.MAX_VALUE)))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(
                                                                jPanel1Layout
                                                                        .createSequentialGroup()
                                                                        .addGroup(
                                                                                jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(
                                                                                                jPanel1Layout
                                                                                                        .createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                jLabel9)
                                                                                                        .addGap(
                                                                                                                18,
                                                                                                                18,
                                                                                                                18)
                                                                                                        .addComponent(
                                                                                                                business,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                143,
                                                                                                                Short.MAX_VALUE))
                                                                                        .addGroup(
                                                                                                jPanel1Layout
                                                                                                        .createSequentialGroup()
                                                                                                        .addComponent(
                                                                                                                jLabel11)
                                                                                                        .addGap(
                                                                                                                18,
                                                                                                                18,
                                                                                                                18)
                                                                                                        .addComponent(
                                                                                                                twoset,
                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                143,
                                                                                                                Short.MAX_VALUE))
                                                                                        .addGroup(
                                                                                                jPanel1Layout
                                                                                                        .createSequentialGroup()
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                        .addGroup(
                                                                                                                jPanel1Layout
                                                                                                                        .createParallelGroup(
                                                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                        .addGroup(
                                                                                                                                jPanel1Layout
                                                                                                                                        .createSequentialGroup()
                                                                                                                                        .addComponent(
                                                                                                                                                jLabel14)
                                                                                                                                        .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                        .addComponent(
                                                                                                                                                twoprice,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                132,
                                                                                                                                                Short.MAX_VALUE))
                                                                                                                        .addGroup(
                                                                                                                                jPanel1Layout
                                                                                                                                        .createSequentialGroup()
                                                                                                                                        .addComponent(
                                                                                                                                                jLabel10)
                                                                                                                                        .addPreferredGap(
                                                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                                                        .addComponent(
                                                                                                                                                businessprice,
                                                                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                                                132,
                                                                                                                                                Short.MAX_VALUE)))))
                                                                        .addGap(
                                                                                30,
                                                                                30,
                                                                                30))
                                                        .addGroup(
                                                                jPanel1Layout
                                                                        .createSequentialGroup()
                                                                        .addComponent(
                                                                                jLabel7)
                                                                        .addPreferredGap(
                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(
                                                                                starttime,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                143,
                                                                                Short.MAX_VALUE)
                                                                        .addGap(
                                                                                31,
                                                                                31,
                                                                                31))
                                                        .addGroup(
                                                                jPanel1Layout
                                                                        .createSequentialGroup()
                                                                        .addComponent(
                                                                                jLabel2)
                                                                        .addGap(
                                                                                5,
                                                                                5,
                                                                                5)
                                                                        .addComponent(
                                                                                enddate,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                143,
                                                                                Short.MAX_VALUE)
                                                                        .addGap(
                                                                                31,
                                                                                31,
                                                                                31))
                                                        .addGroup(
                                                                jPanel1Layout
                                                                        .createSequentialGroup()
                                                                        .addComponent(
                                                                                jLabel5)
                                                                        .addGap(
                                                                                18,
                                                                                18,
                                                                                18)
                                                                        .addComponent(
                                                                                startlocat1,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                143,
                                                                                Short.MAX_VALUE)
                                                                        .addGap(
                                                                                30,
                                                                                30,
                                                                                30)))));
        jPanel1Layout
                .setVerticalGroup(jPanel1Layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(
                                jPanel1Layout
                                        .createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(
                                                jLabel3,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                38,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(
                                                                date,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2)
                                                        .addComponent(
                                                                enddate,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel4)
                                                        .addComponent(
                                                                train_number,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel5)
                                                        .addComponent(
                                                                startlocat1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7)
                                                        .addComponent(
                                                                starttime,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(
                                                                startlocat,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel8)
                                                        .addComponent(
                                                                endtime,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(
                                                                business,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(kkk)
                                                        .addComponent(jLabel11)
                                                        .addComponent(
                                                                twoset,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(
                                                                oneset,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel12)
                                                        .addComponent(
                                                                oneset1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(
                                                                businessprice,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel10))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel13)
                                                        .addComponent(jLabel14)
                                                        .addComponent(
                                                                one_price,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(
                                                                twoprice,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(
                                                jPanel1Layout
                                                        .createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel15)
                                                        .addComponent(
                                                                standprice,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(48, 48, 48)
                                        .addComponent(
                                                jButton1,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                33, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING).addComponent(
                jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>
    //GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
        // TODO add your handling code here:
        String oneset2=oneset.getText();//一等座
        String oneset3=oneset1.getText();//无座
        String twoset1=twoset.getText();
        String business1=business.getText();
        String endtime1=endtime.getText();
        String starttime1=starttime.getText();
        String endlocat1=startlocat.getText();//目的地
        String startlocat2=startlocat1.getText();//出发地
        String train_num=train_number.getText();
        String enddate1=enddate.getText();
        String startdate1=date.getText();
        String business_set_price=businessprice.getText();
        String one_set_price=one_price.getText();
        String two_set_price=twoprice.getText();
        String stand_set_price=standprice.getText();
        Client.inserttrain(startdate1,enddate1,train_num,startlocat2,endlocat1,starttime1,endtime1,business1,oneset2,twoset1,oneset3,business_set_price,one_set_price,two_set_price,stand_set_price);
        JOptionPane.showMessageDialog(null, "添加列车成功");
        dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newtrain().setVisible(true);
            }
        });
    }

    //GEN-BEGIN:variables
    // Variables declaration - do not modify
    public javax.swing.JTextField business;
    private javax.swing.JTextField businessprice;
    public javax.swing.JTextField date;
    public final javax.swing.JTextField enddate = new javax.swing.JTextField();
    public javax.swing.JTextField endtime;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kkk;
    private javax.swing.JTextField one_price;
    public javax.swing.JTextField oneset;
    public javax.swing.JTextField oneset1;
    private javax.swing.JTextField standprice;
    public javax.swing.JTextField startlocat;
    public javax.swing.JTextField startlocat1;
    public javax.swing.JTextField starttime;
    public javax.swing.JTextField train_number;
    private javax.swing.JTextField twoprice;
    public javax.swing.JTextField twoset;
    // End of variables declaration//GEN-END:variables

}